### ISSUE TITLE
Update to feed-io version 6

### ISSUE THREAD

**Issue by ardentsword** [alexdebril/rss-atom-bundle#213]
I assume there are plans to update this package to version 6 of feed-io as well?

If you could use help with this I can take a look as well, if so, could you give some pointers as what to look out for?

**Comment by ardentsword** [comment]
I have experimented with this a bit today, simply updating feed-io and modifying the services.yml to:
```yaml
    http.client:
        class: Symfony\Component\HttpClient\HttplugClient

    feedio.client:
        class: FeedIo\Adapter\Http\Client
        arguments: ['@http.client']
```
(And of course installing the symfony http client in this case with the psr-7 adapter, nyholm/psr7)
But my knowledge of symfony packages is too limited here.

What would be a nice way to make this configurable? 
Manually injecting a service in the project service.yml seems very convoluted
I though maybe about a sort of 'config factory', that injects to correct client adapter based on a configurable string?
I also noticed php-http has a discovery plugin for this: https://docs.php-http.org/en/latest/discovery.html, perhaps that would be a nice default injection?

Let me know what you think!
